server {
    listen 80;
    listen [::]:80;
    server_name 77.110.119.154;

    root /var/www/tether-assets;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|webp)$ {
        expires 7d;
        add_header Cache-Control "public";
    }
}
